name: Sidebar
version: '1.0-SNAPSHOT'
main: org.ncc.sidebar.Main
api-version: '1.21'
authors: [ NatJerry ]
folia-supported: true
softdepend:
  - PlaceHolderAPI

commands:
  sidebar:
    description: "the command of Sidebar"
    aliases:
      - sb
    usage: "/sidebar [args] [...]"
